services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
  telestickers-api:
    container_name: telestickers-api
    image: dbln9/telestickers-api
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/telestickers
  telestickers-bot-sql:
    image: dbln9/telestickers-bot-sql
    container_name: telestickers-bot-sql
    depends_on:
      - telestickers-api
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db: